# Generated by Django 5.2 on 2025-05-01 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('color', models.CharField(choices=[('#808080', '灰色'), ('#ff6961', '赤色'), ('#ffb480', '橙色'), ('#f8f38d', '黄色'), ('#42d6a4', '緑色'), ('#08cad1', '水色'), ('#59adf6', '青色'), ('#9d94ff', '紫色'), ('#c780e8', '桃色')], max_length=30, verbose_name='教练色')),
                ('contract_type', models.CharField(choices=[('管理', '管理'), ('教练', '教练'), ('其他', '其他')], default='教练', max_length=50, verbose_name='职务')),
                ('fullname', models.CharField(blank=True, max_length=20, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='邮箱')),
                ('wechat', models.CharField(blank=True, max_length=20, verbose_name='微信')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='Whatsapp')),
                ('line', models.CharField(blank=True, max_length=20, verbose_name='LINE')),
                ('ski_system', models.CharField(choices=[('加拿大', '加拿大'), ('新西兰', '新西兰'), ('澳洲', '澳洲'), ('日本', '日本'), ('其他', '其他'), ('无', '无')], default='加拿大', max_length=50, verbose_name='双板体系')),
                ('snowboard_system', models.CharField(choices=[('加拿大', '加拿大'), ('新西兰', '新西兰'), ('澳洲', '澳洲'), ('日本', '日本'), ('其他', '其他'), ('无', '无')], default='加拿大', max_length=50, verbose_name='单板体系')),
                ('ski', models.CharField(choices=[('双板无极', '双板无极'), ('双板1级', '双板1级'), ('双板2级', '双板2级'), ('双板3级', '双板3级'), ('双板4级', '双板4级')], default='双板1级', max_length=50, verbose_name='级别')),
                ('snowboard', models.CharField(choices=[('单板无极', '单板无极'), ('单板1级', '单板1级'), ('单板2级', '单板2级'), ('单板3级', '单板3级'), ('单板4级', '单板4级')], default='单板1级', max_length=50, verbose_name='级别')),
                ('accommodation', models.CharField(blank=True, max_length=20, verbose_name='宿舍')),
                ('years_choices', models.CharField(choices=[('1年', '1年'), ('2年', '2年'), ('3年', '3年'), ('4年', '4年'), ('5年以上', '5年以上')], default='1年', verbose_name='経験年数')),
                ('fare_percentage', models.CharField(choices=[('20%', '20%'), ('21.5%', '21.5%'), ('23%', '23%'), ('24.5%', '24.5%'), ('26%', '26%'), ('30%', '30%'), ('31.5%', '31.5%'), ('33%', '33%'), ('34.5%', '34.5%'), ('36%', '36%'), ('40%', '40%'), ('41.5%', '41.5%'), ('43%', '43%'), ('44.5%', '44.5%'), ('46%', '46%')], default='20%', max_length=50, verbose_name='提成比率')),
                ('full_attendance', models.CharField(choices=[('3%', '3%'), ('0%', '0%')], default='3%', max_length=50, verbose_name='全勤提成')),
                ('customers_evaluation', models.CharField(choices=[('2%', '2%'), ('0%', '0%')], default='2%', max_length=50, verbose_name='客人評価')),
                ('company_evaluation', models.CharField(choices=[('5%', '5%'), ('0%', '0%')], default='5%', max_length=50, verbose_name='公司評価')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='現役中')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField(default=0, null=True, verbose_name='课次')),
                ('client', models.CharField(max_length=255, verbose_name='客人姓名')),
                ('lesson_type', models.CharField(choices=[('初学', '初学'), ('初级', '初级'), ('中级', '中级'), ('上级', '上级'), ('导滑', '导滑')], default='初学', max_length=50, verbose_name='课程类型')),
                ('address', models.CharField(max_length=255, verbose_name='酒店')),
                ('place', models.CharField(choices=[('比洛夫', '比洛夫'), ('花园', '花园'), ('安努', '安努'), ('莫伊哇', '莫伊哇'), ('留寿都', '留寿都'), ('喜乐乐', '喜乐乐'), ('其他', '其他')], default='比洛夫', max_length=50, verbose_name='雪场')),
                ('payment_type', models.CharField(choices=[('現金', '現金'), ('刷卡', '刷卡'), ('電子支付', '電子支付'), ('未支付', '未支付')], default='未支付', max_length=50, verbose_name='付款方式')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='付款金額')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='付款日')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('start_date', models.DateTimeField(verbose_name='開始日')),
                ('end_date', models.DateTimeField(verbose_name='終了日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時間')),
                ('finished', models.BooleanField(default=False, verbose_name='終了')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('instructors', models.ManyToManyField(related_name='instructors', to='manager_app.profile')),
            ],
        ),
    ]
