# Generated by Django 5.2 on 2025-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ski',
            field=models.CharField(choices=[('双板0极', '双板0极'), ('双板1级', '双板1级'), ('双板2级', '双板2级'), ('双板3级', '双板3级'), ('双板4级', '双板4级')], default='双板1级', max_length=50, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='snowboard',
            field=models.CharField(choices=[('单板0极', '单板0极'), ('单板1级', '单板1级'), ('单板2级', '单板2级'), ('单板3级', '单板3级'), ('单板4级', '单板4级')], default='单板1级', max_length=50, verbose_name='级别'),
        ),
    ]
